url: http://kljacobs.github.io

# Site settings
title: Keri Jacobs
email: your-email@domain.com
description: "I am an assistant professor and cooperatives extension economist in the Department of Economics at Iowa State University and hold the Iowa Institute for Cooperatives Economics Professorship.  My current appointment began in late 2012 and is a 50% extension, 35% research, and 15% teaching appointment with a focus on cooperatives.  To fulfill this appointment, I teach an undergraduate course on cooperatives (Econ 332 Cooperatives), conduct research on cooperative businesses with a focus on ownership and capital structure, and am developing an extension program to address the needs of cooperatives in our state."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A8AAA5
  secondary: A8AAA5
  secondary-dark: 333
  nav: 1591A6

images:
  background: ../img/header-bg5.jpg

# Build settings
markdown: kramdown
permalink: pretty
